apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-m1r8lt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-m1r8lt
  namespace: my-nginx-m1r8lt
  labels:
    name: nginx-m1r8lt
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-m1r8lt
  template:
    metadata:
      namespace: my-nginx-m1r8lt
      labels:
        name: nginx-m1r8lt
    spec:
      containers:
      - name: nginx-m1r8lt
        image: nginx
        ports:
        - containerPort: 80

